# filters.conf
[FILTER]
Name kubernetes
Match kube.*
Merge_Log On
K8S_Logging.Parser On

[FILTER]
Name lua
Match *
call cb_print
script
function cb_print(tag, timestamp, record)
new_record = record
new_record["processed"] = "by Lua"
return 1, timestamp, new_record
end