# inputs.conf
[INPUT]
Name tail
Path /var/log/app.log
Tag app.logs
Mem_Buf_Limit 5MB
Read_From_Head On
Parser json

[INPUT]
Name cpu
Tag cpu.metrics
Interval_Sec 5

[INPUT]
Name dummy
Dummy {"message": "dummy log"}
Tag dummy.logs
Samples 10

[INPUT]
Name systemd
Tag host.*
Path /var/log/journal
Read_From_Tail On
DB /var/log/systemd.db

[INPUT]
Name fluentbit_metrics
Tag fb.metrics
Scrape_Interval 2
Scrape_On_Start On