# outputs.conf
[OUTPUT]
Name stdout
Match *

[OUTPUT]
Name elasticsearch
Match es.*
Host 192.168.1.100
Port 9200
Index my_index
HTTP_User user
HTTP_Passwd pass

[OUTPUT]
Name http
Match http.*
Host 192.168.1.101
Port 80
Uri /logs
Format json
Json_Date_Key timestamp

[OUTPUT]
Name file
Match file.*
Path /var/log/fluentbit.out
Format csv

[OUTPUT]
Name null
Match null.*